id: P78DA8856
initial_creation_type: ocr
source_metadata:
  volumes:
    27f0193dd72d42adb402f25807b50349:
      base_file: v027.txt
      image_group_id: I1PD95872
      title: རྩ་བའི་ལྟུང་བའི་རྒྱ་ཆེར་འགྲེལ་པ།
      total_pages: 1953
      volume_number: 27
